### ISSUE TITLE
small seek difference in ogm

### ISSUE THREAD

**Issue by michaelni** [dwbuiten/FFmpeg#26]
libavformat/seek-test-ref ~/tickets/2739/lavf_ogm_seeking_borked.ogm
differs in one line
 ret: 0         st: 1 flags:0  ts: 2.576667
-ret: 0         st: 1 flags:1 dts: 2.785333 pts: 2.785333 pos: 559697 size:   255
+ret: 0         st: 1 flags:1 dts: 2.444000 pts: 2.444000 pos: 481596 size:   269

https://samples.mplayerhq.hu/ffmpeg-bugs/trac/ticket2739/lavf_ogm_seeking_borked.ogm

**Comment by dwbuiten** [comment]
I am inclined to say this has changed in a benign way. The headers mismatch for streams in this file, and the seeking changes slightly due to where stuff is updated, but it's actually more accurate here, as far as I can tell, since the first packet after the seek now has a timestamp less than the desired seek point, allowing the API user to actually decode up to that point and display it, whereas before, it was past the desired seekpoint, making displaying it impossible.

I'm going to close this, but if you think it is a larger issue than I do, let me know.
